### ISSUE TITLE
dev branch is behind master branch

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/challengeutils#10]
I want to contribute a utility function (see https://sagebionetworks.jira.com/browse/CHALLENGE-86) but the dev branch is quite a few commits behind the master branch. It would be best if I could submit my PR to the dev branch and later merge dev with master.

I think a rebase should do the trick.

**Comment by kdaily** [comment]
See #12 - @thomasyu888 can we implement to help out @philerooski?

**Comment by thomasyu888** [comment]
Done.
