### ISSUE TITLE
Show URL to resources created after creating challenge

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challengeutils#127]
Once the challenge and all its resources have been created by `challengeutils createchallenge`, it would be user friendly to display the URL to the resources (staging site, prod site, teams, etc.) just before returning. For example

```
...
Challenge name (prod site): URL
Challenge name (staging site): URL
Challenge name Admin (team): URL
Challenge name Participants (team): URL
...
```

These information can be retrieved from the current log. The suggested solution would save the user of `challengeutils` from scrolling through the logs.

**Comment by thomasyu888** [comment]
Good suggestion. I also think there are too many logs being output currently.
