### ISSUE TITLE
Rename the command line functions calls

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/challengeutils#144]
Calls like:
```
challengeutils setevaluationquota
challengeutils killdockeroverquota
challengeutils downloadsubmission
```

Should probably just be
```
challengeutils set-evaluation-quota
challengeutils kill-docker-over-quota
challengeutils download-submission
```

This will be a breaking change.

**Comment by vpchung** [comment]
While we're at it, we should standardize the parameter names and short flags as well, e.g.

- **mirrorwiki** uses `--forceupdate` with no short flag vs. **annotatesubmission** uses `--force` with the short flag, `-f`

**Comment by thomasyu888** [comment]
Good catch, I actually update `--forceupdate` to `--force` in #143 so might as well add the `-f`
