### ISSUE TITLE
Use relative path for markdown_path in wiki_config.json

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challengeutils#208]
**Is your feature request related to a problem? Please describe.**
I'm using the command `challengeutils download-wiki syn_id` to pull wiki pages in markdown format. In the file `wiki_config.json` created, each markdown page has a JSON object with the property `markdown_path` that specifies the location of the file. The way the pull method is implemented, markdown files are located where the command is run, which is the same folder where the file is created `wiki_config.json`.

The issue stems from the fact that `markdown_path` is an absolute path. The issue is because I'm hosting the markdown files on GitHub, someone else who clones the repo and want to push markdown pages to Synapse would need to manually update `markdown_path` values.

**Describe the solution you'd like**
Use relative path for `markdown_path` instead of absolute path. The path should be relative to the location of `wiki_config.json`.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by thomasyu888** [comment]
Thanks @tschaffter ,  Currently, I have

```
--markdown_location
--config_path
```

as parameters, do you find it necessary to have `--config_path`?  If i just download everything into `markdown_location` and the config file that is always created `wiki_config.json`,  then it will further simplify the code.

**Comment by tschaffter** [comment]
I think that adding the option `--markdown_location` (better: `--markdown_dir` or `--workdir`) is enough. Keeping `wiki_config.json` in the same folder as the markdown file is a good idea for now.

Running `challengeutils download-wiki syn_id --workdir ./plop` will create the folder `plop` with all the files in
Running `challengeutils challengeutils sync-wiki syn_id --workdir ./plop` will push the content to synapse

Using the folder specified by `--workdir` or similar for both pull and push command is more consistent that using it only for pull and then rely on `wiki_config.json` for the push as done now.

Also, `push` and `pull` are more widespread today than the terms `download` and `sync`:

- `challengeutils pull-wiki syn_id ...`
- `challengeutils push-wiki syn_id ...`

**Comment by thomasyu888** [comment]
Thanks @tschaffter .  Great feedback - I will incorporate these changes.
