### ISSUE TITLE
Wrong version is installed using python-3.10

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/challengeutils#234]
**Describe the bug**
 If I install `challengeutils` with conda python3.10, it just automatically installs v1.6.0 without errors. If I force to install `v4.1.0` : `pip install challengeutils==4.1.0` , then the error raised: "requires python >=3.6, <3.9".

**To Reproduce**
```console
conda create -n py3.10 python=3.10
conda activate py3.10
pip install --upgrade pip
pip install challengeutils
/Users/rchai/opt/anaconda3/envs/py3.10/bin/challengeutils -v
challengeutils 1.6.0
```

**Expected behavior**
Not quite sure if it's a bug from `conda` itself or the `challengeutils`. The error should be raised if installing with unsatisfied versions of python, rather than installing `v1.6.0`?

**Comment by thomasyu888** [comment]
@rrchai, @trberg.  This is because of [this line of code](https://github.com/Sage-Bionetworks/challengeutils/blob/0a46c958ed643f49cd0138853b6e5cc8aa6df662/setup.cfg#L40).  An update to this code will allow for python 3.10.
