### ISSUE TITLE
Update createchallenge to Leverage new challenge portal

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/challengeutils#251]
**Is your feature request related to a problem? Please describe.**
the Challenge Portal can be found here: https://staging.challenges.synapse.org/

A challenge administrator should use the [example challenge project](https://www.synapse.org/#!Synapse:syn51208606) structure (and annotations) as a guide.

Once they have a new Synapse Project that they would like to include in the Challenge portal, the Project should be added to the [Challenge Project View](https://www.synapse.org/#!Synapse:syn51476218/tables/) that drives the Challenge portal.  Anyone at Sage Bionetworks can do this by selecting Show Scope of Project View from the dropdown menu, clicking Edit Scope, and then adding their Synapse Project.

Some annotations point to wikis, and others point to Synapse tables (Submissions View for the Leaderboard, and various MVs pointing to the People table):

![image](https://github.com/Sage-Bionetworks/challengeutils/assets/10556275/cd6016e2-4149-4742-9773-5230c0e7cd93)

![image](https://github.com/Sage-Bionetworks/challengeutils/assets/10556275/1d5a63e5-a18b-4e92-9aab-b2e0f9b29ead)

**Describe the solution you'd like**
Update the createchallenge functions

**Describe alternatives you've considered**
Wait for synapseformation to create a template to create challenges

**Comment by vpchung** [comment]
Completed with #252
