### ISSUE TITLE
Fix dead link to createChallenge.py in Synapse doc

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challengeutils#32]
The link behind "createChallenge.py" is dead in https://docs.synapse.org/articles/challenge_administration.html.

This issue was originally reported here: https://sagebionetworks.jira.com/browse/SWC-4729

**Comment by thomasyu888** [comment]
View https://github.com/Sage-Bionetworks/synapseDocs/pull/528.
