### ISSUE TITLE
challengeutils query returns malformed csv

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/challengeutils#38]
Because it sticks welcome information at the top, so the top two lines of stdout become: 

```
Welcome, Robert Allaway!

```

**Comment by kdaily** [comment]
https://github.com/Sage-Bionetworks/challengeutils/blob/7032f4f44709bc1b19d997f07aedd01b5cca84e3/challengeutils/__main__.py#L243

Should be:

```
syn = synapseclient.login(silent=True)
```

**Comment by kdaily** [comment]
Probably this one too:

https://github.com/Sage-Bionetworks/challengeutils/blob/7032f4f44709bc1b19d997f07aedd01b5cca84e3/challengeutils/__main__.py#L246

**Comment by thomasyu888** [comment]
@kdaily Done in #39
