### ISSUE TITLE
Add inline python functions from ChallengeWorkflowTemplate

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/challengeutils#50]
per @andrewelamb and his work with the templates, the fact that toil requires the use of 2.7 doesn't mean that the tools used in the workflow should fall under this restriction.
* get docker configuration
* download submission

**Comment by andrewelamb** [comment]
Validate docker
Run Docker

**Comment by thomasyu888** [comment]
#86

**Comment by thomasyu888** [comment]
All workflows that can be run in containers are now run in containers.
