### ISSUE TITLE
Link to Synapse documentation on Challenge Infrastructure

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/challengeutils#69]
`challengeutils createchallenge` Does a lot of things, but what I do once it's done is not clear from the help message or the repository's README. We should link to the Challenge Infrastructure Synapse docs near the beginning of the README since it explains what to do with all the entities created by `createchallenge` https://docs.synapse.org/articles/challenge_administration.html

**Comment by thomasyu888** [comment]
#103

**Comment by thomasyu888** [comment]
Will be released in #120
